export const permissionsMap: Record<string, string> = {
  "/students": "user_read",
  "/students/subscriptions": "order_read",
  "/students/renewals": "renewals",
  "/teachers": "instructor_read",
  "/teachers/improve": "improve",
  "/teachers/requests/info": "requests",
  "/programs": "program_read",
  "/programs/create": "program_create",
  "/messages": "chat",
  "/financials": "financials",
  "/financials/instructors/salaries": "financials",
  "/complaints": "complaints",
  "/ads": "ads",
  "/hr/roles": "roles",
  "/hr/clients": "clients",
  "/hr/instructors/salaries": "instructors-salaries",
  "/hr/departments": "departments",
  "/monitoring": "monitoring",
  "/monitoring/current-lectures": "current-lectures",
  "/monitoring/teacher-reports": "teacher-reports",
  // "/sessions": "sessions",
  "/settings/general": "permission_read",
  "/settings/countries": "country_read",
  "/settings/specializations": "specialization_read",
  "/settings/payment-methods": "paymentMethod_read",
  "/settings/cancel-sessions": "reasonCancelSession_read",
  "/settings/user-responses": "userResponse_read",
  "/settings/sessions-time": "program_read",
  "/settings/coupons": "coupon_read",
  "/settings/notifications": "notifications_read",
  "/settings/transfers": "instructorPaymentMethod_read",
};
