# name: Sync to GitLab

# on:
#   push:
#     branches:
#       - main
#   workflow_dispatch:  # Allow manual triggering

# jobs:
#   sync:
#     runs-on: ubuntu-latest
    
#     steps:
#       - name: Checkout GitHub repo
#         uses: actions/checkout@v4
#         with:
#           fetch-depth: 0  # Get full history for proper syncing
#           token: ${{ secrets.GITHUB_TOKEN }}

#       - name: Configure Git
#         run: |
#           git config --global user.name "${{ secrets.GITLAB_USERNAME }}"
#           git config --global user.email "mahmoudqotb123@gmail.com"
#           git config --global init.defaultBranch main

#       - name: Add GitLab remote
#         run: |
#           git remote add gitlab https://${{ secrets.GITLAB_USERNAME }}:${{ secrets.GITLAB_TOKEN }}@gitlab.com/mahmoudqotb123/Client_Dashboard.git || true
#           git remote set-url gitlab https://${{ secrets.GITLAB_USERNAME }}:${{ secrets.GITLAB_TOKEN }}@gitlab.com/mahmoudqotb123/Client_Dashboard.git

#       - name: Fetch GitLab repository
#         run: |
#           git fetch gitlab || echo "Initial fetch - GitLab repo might be empty"

#       - name: Check GitLab repository status
#         id: check_gitlab
#         run: |
#           if git ls-remote --exit-code gitlab main; then
#             echo "gitlab_has_main=true" >> $GITHUB_OUTPUT
#             echo "GitLab repository has main branch"
#           else
#             echo "gitlab_has_main=false" >> $GITHUB_OUTPUT
#             echo "GitLab repository is empty or has no main branch"
#           fi

#       - name: Force push to empty GitLab repository
#         if: steps.check_gitlab.outputs.gitlab_has_main == 'false'
#         run: |
#           echo "Performing initial push to GitLab..."
#           git push gitlab main --force

#       - name: Sync with existing GitLab repository
#         if: steps.check_gitlab.outputs.gitlab_has_main == 'true'
#         run: |
#           echo "GitLab repository exists, checking for differences..."
          
#           # Check if we're ahead, behind, or diverged
#           git fetch gitlab main
          
#           BEHIND=$(git rev-list --count HEAD..gitlab/main)
#           AHEAD=$(git rev-list --count gitlab/main..HEAD)
          
#           echo "Local is $AHEAD commits ahead and $BEHIND commits behind GitLab"
          
#           if [ "$BEHIND" -eq 0 ] && [ "$AHEAD" -gt 0 ]; then
#             echo "Local is ahead - performing fast-forward push"
#             git push gitlab main
#           elif [ "$BEHIND" -gt 0 ] && [ "$AHEAD" -eq 0 ]; then
#             echo "Local is behind - this shouldn't happen in a mirror setup"
#             echo "Attempting to reset GitLab to match GitHub"
#             git checkout -B temp-sync-branch
#             git push gitlab temp-sync-branch
#             git push gitlab :main || true
#             git push gitlab temp-sync-branch:main
#             git push gitlab :temp-sync-branch
#             git checkout main
#           elif [ "$BEHIND" -gt 0 ] && [ "$AHEAD" -gt 0 ]; then
#             echo "Repositories have diverged - attempting force push with fallback"
#             if ! git push gitlab main --force-with-lease; then
#               echo "Force push failed due to branch protection. Using branch replacement method..."
#               git checkout -B temp-sync-branch
#               git push gitlab temp-sync-branch --force
#               git push gitlab :main || true
#               git push gitlab temp-sync-branch:main
#               git push gitlab :temp-sync-branch || true
#               git checkout main
#             fi
#           else
#             echo "Repositories are in sync"
#           fi

#       - name: Verify sync success
#         run: |
#           git fetch gitlab main
#           if git diff --quiet HEAD gitlab/main; then
#             echo "✅ Sync successful - GitLab is now in sync with GitHub"
#           else
#             echo "❌ Sync verification failed"
#             exit 1
#           fi

#       - name: Report sync status
#         if: always()
#         run: |
#           if [ "${{ job.status }}" = "success" ]; then
#             echo "🎉 GitLab repository successfully synced!"
#           else
#             echo "⚠️ Sync failed. Check the logs above for details."
#             echo "Common issues:"
#             echo "- Invalid GitLab credentials"
#             echo "- Network connectivity issues"
#             echo "- Repository access permissions"
#           fi
